services:
    counter-strike:
        container_name: counter-strike

        # Keeps the HLDS console attached
        stdin_open: true
        tty: true

        # Pasta results in minimal latency whilst still allowing for port mapping
        network_mode: "pasta"
        ports:
            - "27015:27015/udp"
            - "27015:27015/tcp"

        # Volume where all the files and configs live
        volumes:
            - ./cstrike:/opt/hlds/cstrike:U,Z

        # Automatically restart on reboot
        restart: always

        # Build and run
        build: .
        command: >
            ./hlds_run
            -game cstrike
            +ip 0.0.0.0
            +map de_dust2
            +maxplayers 32
            +sv_lan 0
            +exec server.cfg
